import Head from "next/head";
import React from "react";
import styles from "@/styles/Global.module.css";

const BlogPosts = () => {
  return (
    <>
      <main>
        <Head>
          <title>Blog</title>
          <meta name="description" content="Generated by create blog app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/thierno.png" />
        </Head>
        <main className={styles.container}>
          
        </main>
      </main>
    </>
  );
};

export default BlogPosts;
