import Head from "next/head";
import styles from "@/styles/Main.module.css";
import WelcomeSection from "@/components/WelcomeSection/WelcomeSection";
import LatestPosts from "@/components/LatestPosts/LatestPosts";
import { BlogPost, getPosts } from "@/utils/helpers";

export const getStaticProps = () => {
  const posts = getPosts().sort(
    (a, b) =>
      Number(new Date(b.data.publishedAt)) -
      Number(new Date(a.data.publishedAt))
  );

  return {
    props: {
      posts,
    },
  };
};

export default function Home({ posts }: { posts: BlogPost[] }) {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create blog app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/thierno.png" />
      </Head>
      <main className={styles.container}>
        <WelcomeSection />
        <LatestPosts posts={posts} />
      </main>
    </>
  );
}
