import Head from "next/head";
import globalStyles from '@/styles/Global.module.css';
import WelcomeSection from "@/components/WelcomeSection/WelcomeSection";


export default function Home() {
  return (
    <>
      <Head> 
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/thierno.png" />
      </Head>
      <main className={globalStyles.container}>
        <WelcomeSection />
      </main>
    </>
  );
}
