import Head from "next/head";
import styles from '@/styles/Global.module.css';


export default function Home() {
  return (
    <>
      <Head> 
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/thierno.png" />
      </Head>
      <main className={styles.container}>
        <h1>Hello World!</h1>
      </main>
    </>
  );
}
